FROM ubuntu:20.04

USER root

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install curl -y \
        && apt-get install telnetd -y \
        && apt-get install nginx -y


EXPOSE 80


COPY index.html /usr/share/nginx/html


VOLUME volumen1



CMD ["/usr/sbin/nginx", "-g", "daemon off;"]