apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-practice
  namespace: grupo4
  labels:
    app: mi-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-namespace
  template:
    metadata:
      labels:
        app: mi-namespace
    spec:
      containers:
        - name: tp-prueba
          image: juanfuentes/k8spractice:v1
          ports:
            - name: web
              containerPort: 90
  